<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NuGetAudit>false</NuGetAudit>
	  <UserSecretsId>abc6bc58-e9e1-4206-8846-335b4d36d1bd</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="jQuery" Version="3.7.1" />
		<PackageReference Include="jQuery.Validation" Version="1.21.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.14.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Features" Version="4.14.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.14.0" />
		
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" Version="4.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="9.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="SweetAlert2" Version="1.0.1" />
		<PackageReference Include="System.ServiceModel.Duplex" Version="6.0.*" />
		<PackageReference Include="System.ServiceModel.Federation" Version="10.0.652802" />
		<PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
		<PackageReference Include="System.ServiceModel.NetTcp" Version="10.0.652802" />
		<PackageReference Include="System.ServiceModel.Security" Version="6.0.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ShahrChap.Core\ShahrChap.Core.csproj" />
		<ProjectReference Include="..\ShahrChap.DataLayer\ShahrChap.DataLayer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Connected Services\" />
		<Folder Include="Pages\Admin\Order\" />
		<Folder Include="wwwroot\images\" />
		<Folder Include="wwwroot\Uploads\Temp\" />
		<Folder Include="wwwroot\Uploads\Orders\" />
		<Folder Include="wwwroot\UserAvatar\" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\AdminTemplate\plugins\jquery\jquery.validate.js">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="wwwroot\AdminTemplate\plugins\jquery\jquery.validate.min.js">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="wwwroot\AdminTemplate\plugins\jquery\jquery.validate.unobtrusive.js">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="wwwroot\AdminTemplate\plugins\jquery\jquery.validate.unobtrusive.min.js">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

</Project>
